spring.application.name=TrainFlowSpringBackend

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true

spring.jpa.hibernate.ddl-auto=update
server.port=8080
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

jwt.token-validity-seconds=3600
jwt.refresh-token-validity-ms=600000
jwt.base64-secret=${JWT_BASE64_SECRET}

